CREATE TABLE IF NOT EXISTS public.dim_city (
    city_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city TEXT NOT NULL UNIQUE,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS public.fact_weather (
    observation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id SMALLINT NOT NULL REFERENCES public.dim_city(city_id),
    observed_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    temperature DOUBLE PRECISION NOT NULL,
    humidity SMALLINT NOT NULL,
    pressure DOUBLE PRECISION NOT NULL,
    wind_speed DOUBLE PRECISION NOT NULL,
    weather_code SMALLINT NOT NULL,
    description TEXT NOT NULL,
    CONSTRAINT uq_fact_weather_city_observed_at UNIQUE (city_id, observed_at)
);

CREATE INDEX IF NOT EXISTS ix_fact_weather_observed_at
    ON public.fact_weather (observed_at);

CREATE SCHEMA IF NOT EXISTS bi;

CREATE OR REPLACE VIEW bi.weather_observations AS
SELECT
    f.observation_id,
    c.city_id,
    c.city,
    c.latitude,
    c.longitude,
    f.observed_at,
    f.ingested_at,
    f.temperature,
    f.humidity,
    f.pressure,
    f.wind_speed,
    f.weather_code,
    f.description
FROM public.fact_weather AS f
JOIN public.dim_city AS c ON c.city_id = f.city_id;